/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package cn.escheduler.common.enums;

/**
 * task node type
 */
public enum TaskType {

    //common component
    SHELL, SQL, SUB_PROCESS, PROCEDURE, MR, SPARK, SPARK2, PYTHON, DEPENDENT,

    //input/output component
    INPUT, OUTPUT,HIVE_INPUT,HIVE_OUTPUT,MYSQL_INPUT,MYSQL_OUTPUT,

    //preprocess component
    WEIGHTED_SAMPLING, RANDOM_SAMPLING, FILTER_AND_MAPPING, STRATIFIED_SAMPLING, JOIN,
    MERGE_COLUMN, UNION, ADD_SERIAL_NUMBER, SPLIT, DEFAULT_FILLING, NORMALIZATION,
    STANDARDIZATION, TYPE_TRASFORMATION, DATA_FILTER,COLUMN_FILTER,GROUP_AGGREGATION,COLUMN_ALTER,
    TIME_SHIFT,TIME_DIFFER,CHARACTER_MERGING,ACCUMULATION_CALCULATOR,TABLE_JOIN,DATA_OFFSET,DATA_DISCRETIZATION,
    SUBSTRING,TIME_FUNCTION,ADD_COLUMN,CHARACTER_REPLACE,DATA_DEDUPLICATION,DATA_NORMALIZATION,

    //feature engineering component
    PRINCIPAL_COMPONENT_ANALYSIS, CHARACTERISTIC_SCALE_TRANSFORM, CHARACTERISTIC_DISCRETENESS,
    FEATURE_ANOMALY_SMOOTHING, STOCHASTIC_FOREST_CHARACTERISTICS_IMPORTANCE, GBDT_CHARACTERISTIC_IMPORTANCE,
    LINEAR_MODELS_CHARACTERISTIC_IMPORTANCE, PREFERENCE_CALCULATION, FILTERING_FEATURE_SELECTION,

    //statistic analysis component
    PERCENTAGE, FULL_TABLE_STATISTICS, PEARSON_COEFFICIENT, HISTOGRAM, DISCRETE_VALUE_CHARACTERISTIC_ANALYSIS,
    T_TEST, CHI_SQUARE_TEST,CORRELATION_COEFFICIENT_MATRIX,KERNEL_DENSITY_ESTIMATION,BASIC_STATISTICS,

    //machine learning component
    LINEAR_SUPPORT_VECTOR_MACHINE,LOGISTIC_REGRESSION, LINEAR_REGRESSION, GBDT_BI_CLASSIFY,K_NEAREST_NEIGHBORS,
    RANDOM_FOREST,NAIVE_BAYES,K_MEANS_CLUSTERING, GBDT_REGRESSION,XGBOOST_REGRESSION, CONFUSION_MATRIX,
    MULTI_CLASSIFICATION_ASSESSMENT, BI_CLASSIFICATION_ASSESSMENT,REGRESSION_MODEL_ASSESSMENT, FORECAST,DECISION_TREE,
    TIME_SERIES_ANALYSIS,

    //deep learning component
    CNN, DNN, LSTM,LSTM_FORECAST,

    //
    TRAFFIC_FLOW,ENTRY_LEAVE_CITY,TRAVEL_TIME,TRAVEL_SPEED,CONGESTION_DELAY_INDEX,BASE_PASS_TIME,ONROAD_URBAN,CORRELATION_ANALYSIS,
    PASS_EFFICIENCY,QUEUE_LENGTH,PARKING_URBAN,RID_IMBALANCE,OVER_FLOW,CONGESTION_MILEAGE,TRAFFIC_CAPACITY,DELAY_TIME,RID_SATURATION
    }
