const treeData = [
  {
    label: '通用工具',
    key: '0-0',
    iconPath: 'icon-tongyonggongju',
    children: [
      {
        moduleId: 'ShellTools',
        label: 'SHELL工具',
        key: '0-0-0',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#FAAD15',
        iconPath: 'icon-shell',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'SHELL',
        desc: ' <p>1.注释：1111</p>\n' +
          '              <p>2.注释：2222</p>\n' +
          '              <p>3.注释：3333</p>\n' +
          '              <p>4.注释：4444</p>'
      },
   /*   {
        moduleId: "SUB_PROCESS",
        label: 'SUB_PROCESS',
        key: '0-0-1',
        icon: 'deployment-unit',
        size: "170*34",
        type: "node",
        x: 0,
        y: 0,
        shape: "customNode",
        color: "#FAAD15",
        iconPath: "icon-zuzhi",
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType:'SUB_PROCESS'
      }, */
     /* {
        moduleId: 'PROCEDURE',
        label: 'PROCEDURE',
        key: '0-0-2',
        icon: 'deployment-unit',
        size: "170*34",
        type: "node",
        x: 0,
        y: 0,
        shape: "customNode",
        color: "#FAAD15",
        iconPath: "icon-chengxuprogram1",
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType:'PROCEDURE'
      }, */
      {
        moduleId: 'SqlTools',
        label: 'SQL工具',
        key: '0-0-3',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#FAAD15',
        iconPath: 'icon-SqlServer',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'SQL'
      },
      {
        moduleId: 'SparkTools',
        label: 'SPARK',
        key: '0-0-4',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#FAAD15',
         iconPath: 'icon-Spark',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'SPARK'
      },
   /*   {
        moduleId: 'SPARK2',
        label: 'SPARK2',
        key: '0-0-5',
        icon: 'deployment-unit',
        size: "170*34",
        type: "node",
        x: 0,
        y: 0,
        shape: "customNode",
        color: "#FAAD15",
         iconPath: "icon-Spark",
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType:'SPARK2'
      }, */
     /* {
        moduleId: 'MapReduce',
        label: 'MapReduce',
        key: '0-0-6',
        icon: 'deployment-unit',
        size: "170*34",
        type: "node",
        x: 0,
        y: 0,
        shape: "customNode",
        color: "#FAAD15",
         iconPath: "icon-mapreduce",
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType:'GeneralTools'
      }, */
      {
        moduleId: 'PythonTolls',
        label: 'PYTHON',
key: '0-0-7',
icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#FAAD15',
         iconPath: 'icon-FontAwesomepython',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'PYTHON'
      }
   /*   {
        moduleId:"Dependent",
        label: 'DEPENDENT', key: '0-0-8', icon: 'deployment-unit',
        size: "170*34",
        type: "node",
        x: 0,
        y: 0,
        shape: "customNode",
        color: "#FAAD15",
         iconPath: "icon-dependent",
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType:'DEPENDENT'
      }, */
    ]
  },
  {
    label: '输入输出',
    key: '1-0',
    iconPath: 'icon-inputOutput',
    children: [
//       {
//         moduleId: 'DataSourceInput',
//         label: '数据源输入',
// key: '0-1-0',
// icon: 'deployment-unit',
//         size: '170*34',
//         type: 'node',
//         x: 0,
//         y: 0,
//         shape: 'customNode',
//         color: '#13C2C2',
//          iconPath: 'icon-input',
//         /* inPoints: [[0, 0.5]], */
//         outPoints: [[1, 0.5]],
//         nodeType: 'INPUT'
//       },
      {
        moduleId:'MysqlInput',
        label: 'Mysql输入', key: '0-1-2', icon: 'deployment-unit',
        size: "170*34",
        type: "node",
        x: 0,
        y: 0,
        shape: "customNode",
        color: "#13C2C2",
        iconPath: "icon-input",
        outPoints: [[1, 0.5]],
        isDoingEnd: true,
        nodeType:'MYSQL_INPUT'
      },
      {
        moduleId: 'MysqlOutput',
        label: 'Mysql输出',
        key: '0-1-1',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#13C2C2',
        iconPath: 'icon-input-back',
        inPoints: [[0, 0.5]],
        isDoingEnd: true,
        nodeType: 'MYSQL_OUTPUT'
      },

      {
        moduleId:'HiveInput',
        label: 'Hive输入', key: '0-1-3', icon: 'deployment-unit',
        size: "170*34",
        type: "node",
        x: 0,
        y: 0,
        shape: "customNode",
        color: "#13C2C2",
        iconPath: "icon-input",
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        isDoingEnd: true,
        nodeType:'HIVE_INPUT'
      },
      {
        moduleId: 'HiveOutput',
        label: 'Hive输出',
        key: '0-1-4',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#13C2C2',
        iconPath: 'icon-input-back',
        inPoints: [[0, 0.5]],
        isDoingEnd: true,
        nodeType: 'HIVE_OUTPUT'
      },
      // {
      //   moduleId: 'DataOutput',
      //   label: '数据输出',
      //   key: '0-1-5',
      //   icon: 'deployment-unit',
      //   size: '170*34',
      //   type: 'node',
      //   x: 0,
      //   y: 0,
      //   shape: 'customNode',
      //   color: '#13C2C2',
      //   iconPath: 'icon-input-back',
      //   inPoints: [[0, 0.5]],
      //   isDoingEnd: true,
      //   nodeType: 'OUTPUT'
      // }
     /* {
        moduleId:'SQLDataOutput',
        label: 'SQL数据输出', key: '0-1-2', icon: 'deployment-unit',
        size: "170*34",
        type: "node",
        x: 0,
        y: 0,
        shape: "customNode",
        color: "#13C2C2",
        iconPath: "icon-SQL",
        inPoints: [[0, 0.5]],
        nodeType:'SQL_OUTPUT'
      }, */
    ]
  },
  {
    label: '预处理组件',
    key: '2-0',
    icon: 'file-sync',
    iconPath: 'icon-shujuyuchuli',
    children: [
      {
        moduleId: 'DataFilter',
        label: '数据过滤',
        key: '0-2-0',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#28A0FF',
        iconPath: 'icon-shujuguolv',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        isDoingStart: true,
        nodeType: 'DATA_FILTER'
      },
      {
        moduleId: 'ColumnFilter',
        label: '列过滤',
        key: '0-2-1',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#28A0FF',
         iconPath: 'icon-shujuguolv1',

        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'COLUMN_FILTER'
      },
      {
        moduleId: 'PacketAggregation',
        label: '分组聚合',
        key: '0-2-2',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
         iconPath: 'icon-fenzujuhe',

        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'GROUP_AGGREGATION'
      },
      {
        moduleId: 'ColumnAlter',
        label: '列名修改',
        key: '0-2-3',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
         iconPath: 'icon-liemingzhuanhuan',

        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'COLUMN_ALTER'
      },
      {
        moduleId: 'TimeShift',
        label: '时间格式转换',
        key: '0-2-4',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
        iconPath: 'icon-shijiangeshizhuanhuan',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'TIME_SHIFT'
      },
      {
        moduleId: 'TimeDiffer',
        label: '时间差',
         key: '0-2-5',
         icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
         iconPath: 'icon-jisuanshijiancha',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'TIME_DIFFER'
      },
      {
        moduleId: 'CharacterMerging',
        label: '字符串拼接',
        key: '0-2-6',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
        iconPath: 'icon-zifupinjie',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'CHARACTER_MERGING'
      },
      {
        moduleId: 'AccumulationCalculator',
        label: '累加计算器',
        key: '0-2-7',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
         iconPath: 'icon-jisuanqi',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'ACCUMULATION_CALCULATOR'
      },
      {
        moduleId: 'TableJoin',
        label: '表关联',
        key: '0-2-8',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
        iconPath: 'icon-biaoguanlian',
        inPoints: [[0, 0.4], [0, 0.6]],
        outPoints: [[1, 0.5]],
        nodeType: 'TABLE_JOIN'
      },
      {
        moduleId: 'DataOffset',
        label: '数据偏移',
        key: '0-2-9',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
        iconPath: 'icon-pianyi',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'DATA_OFFSET'
      },
      {
        moduleId: 'DataDiscretization',
        label: '数据离散化',
        key: '0-2-10',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
        iconPath: 'icon-shujulisanhuahei',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'DATA_DISCRETIZATION'
      },
      {
        moduleId: 'SubString',
        label: '字符串截取',
        key: '0-2-11',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
         iconPath: 'icon-jiequ',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'SUBSTRING'
      },
      {
        moduleId: 'TimeFunction',
        label: '时间函数',
        key: '0-2-12',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
        iconPath: 'icon-shijianhanshu',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'TIME_FUNCTION'
      },
      {
        moduleId: 'AddColumn',
        label: '增加新列',
        key: '0-2-13',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
        iconPath: 'icon-zengjialie',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'ADD_COLUMN'
      },
      {
        moduleId: 'Split',
        label: '比例拆分',
        key: '0-2-14',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
        iconPath: 'icon-chaifen',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.4], [1, 0.6]],
        nodeType: 'SPLIT'
      },
      {
        moduleId: 'DefaultFilling',
        label: '缺省值填充',
        key: '0-2-15',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
        iconPath: 'icon-tianjiaqueshengzhihui',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'DEFAULT_FILLING'
      },
      {
        moduleId: 'CharacterReplace',
        label: '字符串替换',
        key: '0-2-16',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
        iconPath: 'icon-zifutihuan',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'CHARACTER_REPLACE'
      },
      {
        moduleId: 'DataDeduplication',
        label: '数据去重',
        key: '0-2-17',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
        iconPath: 'icon-shujuquzhong',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'DATA_DEDUPLICATION'
      },
      {
        moduleId: 'DataNormalization',
        label: '归一化',
        key: '0-2-18',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1890ff',
        iconPath: 'icon-guiyihua',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'DATA_NORMALIZATION'
      }
    ]
  },
  {
    label: '统计分析',
    key: '3-0',
    icon: 'bar-chart',
    iconPath: 'icon-tongjifenxi',
    children: [
      {
        moduleId: 'NuclearDensityAnalysis',
        label: '核密度估计',
        key: '0-3-0',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#5A6C81',
        iconPath: 'icon-hemidu',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'KERNEL_DENSITY_ESTIMATION'
      },
      {
        moduleId: 'BasicStatistics',
        label: '基本统计信息',
         key: '0-3-1',
         icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#5A6C81',
        iconPath: 'icon-tongjixinxi',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'BASIC_STATISTICS'
      },
      {
        moduleId: 'CorrelationAnalysis',
        label: '相关性分析',
        key: '0-3-2',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-xiangguanxingfenxi',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'CORRELATION_ANALYSIS'
      },
    ]
  },
  {
    label: '机器学习',
    key: '4-0',
    icon: 'team',
    iconPath: 'icon-jiqixuexi',
    children: [
      {
        moduleId: 'RegressionModelEvaluation',
        label: '回归模型评估',
        key: '0-4-0',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1FD6FF',
        iconPath: 'icon-huiguimoxingpinggu',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'REGRESSION_MODEL_ASSESSMENT'
      },
      /* {
        moduleId:'TimeSeriesAnalysis',
        label: '时间序列分析', key: '0-4-1', icon: 'deployment-unit',
        size: "170*34",
        type: "node",
        x: 0,
        y: 0,
        shape: "customNode",
        color: "#1FD6FF",
        iconPath: "icon-shijianxuliefenxi",
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType:'TIME_SERIES_ANALYSIS'
      }, */
      {
        moduleId: 'forecast',
        label: '预测',
        key: '0-4-2',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1FD6FF',
        iconPath: 'icon-yuce',
        inPoints: [[0, 0.4], [0, 0.6]],
        outPoints: [[1, 0.5]],
        nodeType: 'FORECAST'
      },
      {
        moduleId: 'LinearRegression',
        label: '线性回归',
        key: '0-4-3',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1FD6FF',
        iconPath: 'icon-xianxinghuigui',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'LINEAR_REGRESSION'
      },
      {
        moduleId: 'DecisionTree',
        label: '决策树-分类',
        key: '0-4-4',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1FD6FF',
        iconPath: 'icon-jiqixuexi_fenlei_jueceshufenleiqi',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'DECISION_TREE'
      },
      {
        moduleId: 'MultiClassFicationAssessment',
        label: '多分类评估',
        key: '0-4-5',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1FD6FF',
        iconPath: 'icon-duofenleipinggu',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'MULTI_CLASSIFICATION_ASSESSMENT'
      },
      {
        moduleId: 'LogisticRegression',
        label: '逻辑回归',
        key: '0-4-6',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#1FD6FF',
        iconPath: 'icon-luojihuiguisuanfa',
        inPoints: [[0, 0.5]],
        outPoints: [[1, 0.5]],
        nodeType: 'LOGISTIC_REGRESSION'
      }
    ]
  },
  {
    label: '交通指标',
    key: '5-0',
    icon: 'smile',
    iconPath: 'icon-jiaotongzhiyin',
    children: [
      {
        moduleId: 'TrafficFlow',
        label: '交通流量',
        key: '0-5-0',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-traffic',
        inPoints: [[0, 0.4], [0, 0.6]],
        outPoints: [[1, 0.5]],
        nodeType: 'TRAFFIC_FLOW'
      },
      {
        moduleId: 'EntryLeavecity',
        label: '出入城流量',
        key: '0-5-1',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-dangrichuruchengpeizhi',
        inPoints: [[0, 0.4], [0, 0.6]],
        outPoints: [[1, 0.5]],
        nodeType: 'ENTRY_LEAVE_CITY'
      },
      {
        moduleId: 'TravelTime',
        label: '行程时间',
        key: '0-5-2',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-hangchengshijianyuce',
        inPoints: [[0, 0.4], [0, 0.6]],
        outPoints: [[1, 0.5]],
        nodeType: 'TRAVEL_TIME'
      },
      {
        moduleId: 'TravelSpeed',
        label: '行程速度',
        key: '0-5-3',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-sudu',
        inPoints: [[0, 0.4], [0, 0.6]],
        outPoints: [[1, 0.5]],
        nodeType: 'TRAVEL_SPEED'
      },
      {
        moduleId: 'CongestionDelayIndex',
        label: '拥堵延时指数',
        key: '0-5-4',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-yongduzhishu',
        inPoints: [[0, 0.4], [0, 0.6]],
        outPoints: [[1, 0.5]],
        nodeType: 'CONGESTION_DELAY_INDEX'
      },
      {
        moduleId: 'BasePasstime',
        label: '历史通行时长参数',
        key: '0-5-5',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-shichang',
        inPoints: [[0, 0.4], [0, 0.6]],
        outPoints: [[1, 0.5]],
        nodeType: 'BASE_PASS_TIME'
      },
      {
        moduleId: 'OnroadUrban',
        label: '在途量',
        key: '0-5-6',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-daishouhuo',
        inPoints: [[0, 0.4], [0, 0.6]],
        outPoints: [[1, 0.5]],
        nodeType: 'ONROAD_URBAN'
      },
      {
        moduleId: 'PassEfficiency',
        label: '通行效率指数',
        key: '0-5-7',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-tonghangxiaoshuaicanshu',
        inPoints: [[0, 0.4], [0, 0.6]],
        outPoints: [[1, 0.5]],
        nodeType: 'PASS_EFFICIENCY'
      },
      {
        moduleId: 'QueueLength',
        label: '排队长度',
        key: '0-5-8',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-paiduichangdu',
        inPoints: [[0, 0.4], [0, 0.6]],
        outPoints: [[1, 0.5]],
        nodeType: 'QUEUE_LENGTH'
      },
      {
        moduleId: 'ParkingUrban',
        label: '城区驻车量',
        key: '0-5-10',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-tingcheshuliang',
        inPoints: [[0, 0.3], [0, 0.6], [0, 0.9]],
        outPoints: [[1, 0.5]],
        nodeType: 'PARKING_URBAN'
      },
      {
        moduleId: 'RidImbalance',
        label: '路口失衡指数',
        key: '0-5-11',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-imbalance',
        inPoints: [[0, 0.3], [0, 0.6], [0, 0.9]],
        outPoints: [[1, 0.5]],
        nodeType: 'RID_IMBALANCE'
      },
      {
        moduleId: 'OverFlow',
        label: '溢流',
        key: '0-5-12',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-yiliuyuce',
        inPoints: [[0, 0.4], [0, 0.6]],
        outPoints: [[1, 0.5]],
        nodeType: 'OVER_FLOW'
      },
      {
        moduleId: 'CongestionMileage',
        label: '道路路况里程占比',
        key: '0-5-13',
        icon: 'deployment-unit',
        size: '170*34',
        type: 'node',
        x: 0,
        y: 0,
        shape: 'customNode',
        color: '#9254DE',
        iconPath: 'icon-mileage',
        inPoints: [[0, 0.4], [0, 0.6]],
        outPoints: [[1, 0.5]],
        nodeType: 'CONGESTION_MILEAGE'
      }
    ]
  }
]

function getData () {
  return treeData
}

export {
  getData
}
